### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by nahatx** [Appointat/Chat-with-Document-s-using-ChatGPT-API-and-Text-Embedding#4]
https://github.com/Appointat/Chat-with-Document-s-using-ChatGPT-API-and-Text-Embedding/blob/11f2f676ca9f8b780f81bfaf754e3a0a2bebf0fa/Voice%20Chat%20Bot/uiwh.py#L5

Howdy,

Do not expose your API key in your source code.

Instead, consider storing it an environment variable, or using a key management service, or even software such as Vault.
Then be sure to rotate your API key after it is safely stored, or else it may still be recoverable in your commit history.

Also, see Openai's best practices page for api keys for more details:
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Comment by Appointat** [comment]
Thank you guy a lot! You are right it is not safe at all.
